// Build the distributable app from the artifact source.
//
// `tide-of-iron-armybuilder.html` is authored for Claude Artifacts, which wrap
// it in an HTML skeleton at publish time. This script produces a standalone,
// installable PWA:
//   - index.html            (skeleton + PWA <head>/<script> injected)
//   - sw.js                 (service worker, cache name stamped with APP_VERSION)
//   - manifest.webmanifest  (static, copied check only)
//   - icon-192.png / icon-512.png / apple-touch-icon.png  (rasterised from the design)
//   - icon.svg / favicon.svg (static)
//
// Run:  node build.mjs
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import zlib from "node:zlib";

const SRC = "tide-of-iron-armybuilder.html";
const src = readFileSync(SRC, "utf8");

const version = (src.match(/APP_VERSION\s*=\s*'([^']+)'/) || [])[1] || "0";

/* ---------- index.html -------------------------------------------------- */

const i = src.indexOf("</style>");
if (i === -1) throw new Error("no </style> found in " + SRC);
const head = src.slice(0, i + "</style>".length).trim();
const body = src.slice(i + "</style>".length).trim();

const PWA_HEAD = `
<link rel="manifest" href="manifest.webmanifest">
<meta name="theme-color" content="#4C5334">
<link rel="icon" href="favicon.svg" type="image/svg+xml">
<link rel="apple-touch-icon" href="apple-touch-icon.png">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="apple-mobile-web-app-title" content="Battle Builder">`.trim();

const PWA_TAIL = `<script>
if ("serviceWorker" in navigator) {
  addEventListener("load", () => navigator.serviceWorker.register("sw.js").catch(() => {}));
}
</script>`;

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<style>
  :root { color-scheme: light dark; }
  body { margin: 0; font: 14px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; background: #faf9f5; }
  img { max-width: 100%; }
  [hidden] { display: none !important; }
</style>
${PWA_HEAD}
${head}
</head>
<body>
${body}
${PWA_TAIL}
</body>
</html>
`;
writeFileSync("index.html", html);

/* ---------- service worker (cache name stamped with the app version) ---- */

const sw = `/* Auto-generated by build.mjs — do not edit. */
const CACHE = "toi-bb-v${version}";
const ASSETS = [
  "./", "./index.html", "./manifest.webmanifest",
  "./icon.svg", "./favicon.svg", "./icon-192.png", "./icon-512.png", "./apple-touch-icon.png"
];

self.addEventListener("install", (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET") return;
  const sameOrigin = new URL(req.url).origin === location.origin;

  if (sameOrigin) {
    // App shell: cache-first, refresh in the background, fall back to index.html.
    e.respondWith(
      caches.match(req).then((hit) => {
        const net = fetch(req).then((res) => {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(req, copy));
          return res;
        }).catch(() => hit || caches.match("./index.html"));
        return hit || net;
      })
    );
  } else {
    // Google Fonts etc: stale-while-revalidate so the app still styles offline.
    e.respondWith(
      caches.match(req).then((hit) => {
        const net = fetch(req).then((res) => {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(req, copy));
          return res;
        }).catch(() => hit);
        return hit || net;
      })
    );
  }
});
`;
writeFileSync("sw.js", sw);

/* ---------- icons: rasterise the rectangle design to PNG ---------------- */
// Design: full-bleed olive field with 5 stencil bars (centre bar oxide-red),
// echoing the masthead rule. All rectangles, so no anti-aliasing is needed
// and it doubles as a maskable icon (content sits well within the safe zone).

const OLIVE = [0x4c, 0x53, 0x34];
const CREAM = [0xed, 0xe8, 0xda];
const OXIDE = [0xa0, 0x37, 0x1e];

function iconPixels(size) {
  const px = Buffer.alloc(size * size * 4);
  const put = (x, y, [r, g, b]) => {
    const o = (y * size + x) * 4;
    px[o] = r; px[o + 1] = g; px[o + 2] = b; px[o + 3] = 255;
  };
  for (let y = 0; y < size; y++) for (let x = 0; x < size; x++) put(x, y, OLIVE);

  const bars = 5;
  const barW = Math.round(size * 0.066);
  const gapW = Math.round(size * 0.043);
  const totW = bars * barW + (bars - 1) * gapW;
  const x0 = Math.round((size - totW) / 2);
  const bandH = Math.round(size * 0.27);
  const y0 = Math.round((size - bandH) / 2);

  for (let b = 0; b < bars; b++) {
    const bx = x0 + b * (barW + gapW);
    const col = b === 2 ? OXIDE : CREAM;
    for (let y = y0; y < y0 + bandH; y++)
      for (let x = bx; x < bx + barW; x++) put(x, y, col);
  }
  return px;
}

function crc32(buf) {
  let c = ~0;
  for (let i = 0; i < buf.length; i++) {
    c ^= buf[i];
    for (let k = 0; k < 8; k++) c = (c >>> 1) ^ (0xedb88320 & -(c & 1));
  }
  return (~c) >>> 0;
}
function pngChunk(type, data) {
  const t = Buffer.from(type, "ascii");
  const len = Buffer.alloc(4); len.writeUInt32BE(data.length);
  const crc = Buffer.alloc(4); crc.writeUInt32BE(crc32(Buffer.concat([t, data])));
  return Buffer.concat([len, t, data, crc]);
}
function encodePNG(size, rgba) {
  const sig = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(size, 0); ihdr.writeUInt32BE(size, 4);
  ihdr[8] = 8; ihdr[9] = 6; // 8-bit RGBA
  const stride = size * 4;
  const raw = Buffer.alloc(size * (1 + stride));
  for (let y = 0; y < size; y++) {
    raw[y * (1 + stride)] = 0; // filter: none
    rgba.copy(raw, y * (1 + stride) + 1, y * stride, y * stride + stride);
  }
  const idat = zlib.deflateSync(raw, { level: 9 });
  return Buffer.concat([sig, pngChunk("IHDR", ihdr), pngChunk("IDAT", idat), pngChunk("IEND", Buffer.alloc(0))]);
}

for (const s of [192, 512]) writeFileSync(`icon-${s}.png`, encodePNG(s, iconPixels(s)));
writeFileSync("apple-touch-icon.png", encodePNG(180, iconPixels(180)));

for (const f of ["manifest.webmanifest", "icon.svg", "favicon.svg"]) {
  if (!existsSync(f)) console.warn(`! missing static file: ${f}`);
}

console.log(`built v${version}: index.html, sw.js, icon-192/512.png, apple-touch-icon.png`);
